# Copyright 2026 Shenzhen XiaoR Geek Technology Co., Ltd.
# SPDX-License-Identifier: Apache-2.0

/**:
  ros__parameters:
    topic_prefix: /xraudio
    expected_serial: ""
    print_status: true
    print_doa: true
    print_wake: true
